name: rounded_scroll
description: Swipe and scroll in style! RoundedScroll is the perfect widget for your modern Flutter designs. Customize it to your liking and watch it update as you navigate!
version: 1.0.0
repository: https://github.com/dylanroman03/RoundedScroll
# homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  line_awesome_flutter: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  lint: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
